Governing body detail page
lblod/frontend-contact-hub pull request #60
Opened 2021-07-12 19:01 UTC by anitacaron

It requires a change in the backend that is in this [PR](https://github.com/lblod/app-contact-hub/pull/20).

2021-07-13 11:45 UTC, anitacaron commented
I'll update this to use the new card component!

2021-07-13 13:17 UTC, Windvis requested changes

2021-07-13 13:22 UTC, anitacaron commented on app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/index.hbs
> +                  @model={{mandatory.id}}
We discussed it yesterday. 😬

2021-07-13 13:25 UTC, Windvis commented on app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/index.hbs
> +                  @model={{mandatory.id}}
Hmmmmm did we :no_mouth:. I only remember the breadcrumb issue. Le me check

2021-07-13 13:29 UTC, anitacaron commented on app/templates/administrative-units/administrative-unit/governing-bodies/governing-body/index.hbs
> +                  @model={{mandatory.id}}
😬 You said the error is related to the breadcrumb, but I was saying about this link 😬

2021-07-14 08:17 UTC, anitacaron commented on app/routes/administrative-units/administrative-unit/governing-bodies/governing-body.js
> +        'Bestuurslid van het bestuur van de eredienst'
Yes, I'll change it.

2021-07-14 08:21 UTC, anitacaron commented on app/templates/administrative-units/administrative-unit/governing-bodies/governing-body.hbs
> +{{page-title "Bestuursorganen"}}
No, I forgot to change it.

2021-07-14 09:22 UTC, Windvis requested changes

2021-07-14 09:22 UTC, Windvis commented on app/routes/administrative-units/administrative-unit/governing-bodies/governing-body.js
> +      return mandate.get('roleBoard.label') === MEMBER_ROLE_ID;
Should be `roleBoard.id` now I think?

2021-07-14 09:43 UTC, anitacaron commented on app/routes/administrative-units/administrative-unit/governing-bodies/governing-body.js
> +      return mandate.get('roleBoard.label') === MEMBER_ROLE_ID;
ops

2021-07-14 10:15 UTC, merged